Add components
LDouglasOT/MathMagicians pull request #2
Opened 2023-05-04 06:30 UTC by LDouglasOT

**Tasks Completed**

- Build magic magician calculator ui

2023-05-04 06:57 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @LDouglasOT 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use Gitflow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 06:57 UTC, abdulhamiid commented on src/components/Calculator.jsx
> +}
According to the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md), `Calculator.js` should have at least 1 child component. 

![image](https://user-images.githubusercontent.com/78251927/236131011-ac367896-ce7c-4482-abd3-c40c02c9fdf2.png)

- [ ] When writing React component, one of the common things that happen is that the component that we write has become a big fat chunk, causing it harder to read and understand. 👀

- [ ] When that happens, it is always advised that we split the big component into a few smaller components so it is easier to understand. 🛠🤗

- [ ] Please kindly implement that 🛠.

2023-05-04 07:04 UTC, abdulhamiid commented on README.md
> +- LinkedIn: [LdouglasOT](https://www.linkedin.com/in/LdouglasOT/)
The lint to your `Twitter` and `LinkedIn` profiles is broken please kindly fix them. Let's avoid broken links in our repo for a professional repository. 💪 🤗

2023-05-04 07:04 UTC, abdulhamiid commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Please let fix the broken LICENSE link.  🛠

![image](https://user-images.githubusercontent.com/78251927/236133497-2988ad8f-c90d-4756-94f0-38292172ecc7.png)

💡 Public repositories on GitHub are often used to share open-source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software. 👍

2023-05-04 07:04 UTC, abdulhamiid commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
![image](https://user-images.githubusercontent.com/78251927/236133367-c6261954-003a-45b1-b0e3-a391bc96ffff.png)

Please kindly fix the link our our `issue` page. Let's avoid broken links in our repo for a professional repository. 💪 🤗

2023-05-05 04:58 UTC, abdallahmalima approved these changes
Hi @LDouglasOT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- created components folder ✔
- `Calculator.js` has functional component ✔
- `Calculator.js`  have at least 1 child component ✔
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 06:37 UTC, merged